base_model: minpeter/tiny-ko-base

hub_model_id: minpeter/tiny-ko-sft
output_dir: ./outputs/tiny-ko-sft
wandb_project: "axolotl"
wandb_entity: "kasfiekfs-e"

chat_template: chatml
datasets:
  - path: lemon-mint/Korean-FineTome-100k
    type: chat_template
    split: train[:10%]
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: lemon-mint/smol-koreantalk
    type: chat_template
    split: train[:10%]
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: heegyu/open-korean-instructions-v20231020
    type: chat_template
    split: train[:10%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
    roles:
      user: ["human", "user"]
      assistant: ["gpt", "assistant", "bot"]
      system: ["system", "input"]

  # NOTE: https://github.com/FreedomIntelligence/MultilingualSIFT
  - path: FreedomIntelligence/evol-instruct-korean
    type: chat_template
    split: train[:10%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

  - path: FreedomIntelligence/alpaca-gpt4-korean
    type: chat_template
    split: train[:10%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

  - path: FreedomIntelligence/sharegpt-korean
    type: chat_template
    split: train[:10%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

  - path: coastral/korean-writing-style-instruct
    type: chat_template
    split: train[:10%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

  - path: devngho/korean-instruction-mix
    type: chat_template
    split: train[:10%]
    field_messages: messages
    message_property_mappings:
      role: from
      content: value

  - path: youjunhyeok/Magpie-Pro-300K-Filtered-ko
    type: chat_template
    split: train[:10%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

  - path: youjunhyeok/smoltalk-ko-translate
    type: chat_template
    name: merge_filtered
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content

dataset_prepared_path: last_run_prepared
val_set_size: 0.05

save_steps: 200
warmup_steps: 20
eval_steps: 200

sequence_len: 4096

# <<<< experimental settings <<<<
sample_packing: true
train_on_inputs: false
# >>>> experimental settings >>>

pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 16

optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 1e-3

bf16: auto
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

num_epochs: 1
weight_decay: 0.0
