base_model: minpeter/pretrained-tiny-ko

chat_template: chatml
datasets:
  - path: lemon-mint/Korean-FineTome-100k
    type: chat_template
    split: train[:20%]
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: lemon-mint/smol-koreantalk
    type: chat_template
    split: train[:20%]
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: FreedomIntelligence/alpaca-gpt4-korean
    type: chat_template
    split: train[:20%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

dataset_prepared_path: last_run_prepared
val_set_size: 0.05

hub_model_id: minpeter/ko-tiny-exp
output_dir: ./ouputs/ko-tiny-exp
wandb_project: "axolotl"
wandb_entity: "kasfiekfs-e"

save_steps: 200
warmup_steps: 100
eval_steps: 200

sequence_len: 512
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 56

optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

bf16: auto
tf32: false

added_tokens_overrides:
  128001: "<|im_end|>"
  128002: "<|im_start|>"

special_tokens:
  bos_token: <|begin_of_text|>
  eos_token: <|im_end|>
  pad_token: <|im_end|>

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

num_epochs: 4
weight_decay: 0.0
