base_model: minpeter/pretrained-tiny-ko

chat_template: tokenizer_default_fallback_chatml
datasets:
  - path: lemon-mint/Korean-FineTome-100k
    type: chat_template
    split: train[:20%]
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
  - path: lemon-mint/smol-koreantalk
    type: chat_template
    split: train[:20%]
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
dataset_prepared_path: last_run_prepared
val_set_size: 0.05

hub_model_id: minpeter/ko-tiny-exp
output_dir: ./ouputs/ko-tiny-exp
wandb_project: "axolotl"
wandb_entity: "kasfiekfs-e"

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 16

optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

bf16: auto
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_steps: 100
num_epochs: 2
evals_per_epoch: 2
saves_per_epoch: 1
weight_decay: 0.0
