base_model: minpeter/tiny-ko-124m-base-muon

hub_model_id: minpeter/tiny-ko-124m-sft-muon
output_dir: ./outputs/tiny-ko-124m-sft-muon
wandb_project: "axolotl"
wandb_entity: "kasfiekfs-e"

model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

strict: false

chat_template: chatml
datasets:
  - path: HuggingFaceTB/smol-smoltalk
    type: chat_template
    split: train
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: trillionlabs/multisystem-curated
    type: chat_template
    split: train
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: allenai/tulu-3-sft-personas-instruction-following
    type: chat_template
    split: train
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: lemon-mint/smol-koreantalk
    type: chat_template
    split: train
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: lemon-mint/Korean-FineTome-100k
    type: chat_template
    split: train
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

  - path: heegyu/open-korean-instructions-v20231020
    type: chat_template
    split: train
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value
    roles:
      user: ["human", "user"]
      assistant: ["gpt", "assistant", "bot"]
      system: ["system", "input"]

  - path: coastral/korean-writing-style-instruct
    type: chat_template
    split: train
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

  - path: devngho/korean-instruction-mix
    type: chat_template
    split: train
    field_messages: messages
    message_property_mappings:
      role: from
      content: value

dataset_prepared_path: last_run_prepared
val_set_size: 0.001
save_safetensors: true
sequence_len: 2048
sample_packing: false
pad_to_sequence_len: false
use_pose: true
pose_max_context_len: 65536

overrides_of_model_config:
  rope_theta: 10000.0
  max_position_embeddings: 65536

gradient_accumulation_steps: 8
micro_batch_size: 32
num_epochs: 1
optimizer: muon
lr_scheduler: cosine
learning_rate: 3e-4

train_on_inputs: false
group_by_length: false
bf16: true
fp16:
tf32: true

gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
sdp_attention:
s2_attention:

save_steps: 200
warmup_steps: 20
eval_steps: 200
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
